###GET
GET http://localhost:3000/products
##
##
##
##
##
##
##
##
##
##
###POST
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 3",
    "price": 100,
    "description": "This is a test product"
}


##
##
##
##
##
##
##
###PUT
PUT http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "Product 1",
    "price": 233,
    "description": "This is a test product"
}

##
##
##
##
##
##
##
###GET BY ID
GET http://localhost:3000/products/1


##
##
##
##
##
##
##
###DELETE
DELETE http://localhost:3000/products/1


    
