###GET
GET http://localhost:3000/products
##
##
##
##
##
##
##
##
##
##
###POST
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 3",
    "price": 100,
    "description": "This is a test product"
}


##
##
##
##
##
##
##
###PUT
PUT http://localhost:3000/products/25
Content-Type: application/json

{
    "name": "Macbook Pro",
    "price": 10000,
    "description": "Ultra-portátil com processador M3, 16GB de RAM e 1TB de SSD"
}


##
##
##
##
##
##
##
###GET BY ID
GET http://localhost:3000/products/25


##
##
##
##
##
##
##
###DELETE
DELETE http://localhost:3000/products/26


    
