#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Executa lint-staged em ambos os projetos
echo "🔍 Verificando frontend..."
cd frontend && npx lint-staged
echo "✅ Frontend verificado"

echo "🔍 Verificando backend..."
cd ../backend && npx lint-staged
echo "✅ Backend verificado"